org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=createtnt
mod_name=Create TNT
mod_license=MIT
mod_version=1.0.0
mod_group_id=asd.itamio
mod_authors=Itamio, Asd1281yss
mod_description=TNT explodes like artillery shells: huge smoke plumes, blast rays, delayed boom, screen shake, energy-transfer block destruction, structural collapse.
