org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.12.2
forge_version=14.23.5.2847
mappings=stable_39

## Mod Properties
mod_id=tnt_duper
mod_name=TNT Duper
mod_license=MIT
mod_version=1.0.0
mod_group_id=asd.itamio
mod_authors=Itamio, Asd1281yss
mod_description=Allows dispensers to duplicate and dispense TNT infinitely. Place a dispenser with TNT and power it to spawn primed TNT without consuming the item.
