org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.12.2
forge_version=14.23.5.2847
mappings=stable_39

## Mod Properties
mod_id=chunkstructurecopy
mod_name=Chunk Structure Copy
mod_license=MIT
mod_version=1.0.0
mod_group_id=asd.itamio
mod_authors=Itamio, Asd1281yss
mod_description=This mod lets you select chunk regions with /csc chunk1 and /csc chunk2, export them to global NBT files with /csc export, and paste them anywhere with /csc paste using relative coordinates.
