org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=smoothcontainer
mod_name=SmoothContainer
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=asd.itamio
mod_authors=Itamio, Asd1281yss
mod_description=Container GUI Stutter Mitigation - defers container screen initialization over multiple frames to eliminate frametime spikes when opening chests, barrels, furnaces, and other container GUIs.
