org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.12.2
forge_version=14.23.5.2847
mappings=stable_39

## Mod Properties
mod_id=autologinandregister
mod_name=Auto Login & Auto Register
mod_license=All-Rights-Reserved
mod_version=2.1.0
mod_group_id=asd.itamio
mod_authors=Itamio, Asd1281yss
mod_description=Forgot your password again? Have to think of a password for /register again? This mod adds auto register and auto login.
