org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.12.2
forge_version=14.23.5.2847
mappings=stable_39

## Mod Properties
mod_id=optimizeddaycounter
mod_name=Optimized Day Counter
mod_license=MIT
mod_version=1.0.0
mod_group_id=asd.itamio
mod_authors=Itamio, Asd1281yss
mod_description=Shows the current world day and an optional real-life-style Minecraft clock in a movable HUD.
