modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="mod_icon.png"
credits="Asd1281yss"
authors="Itamio, Asd1281yss"
description='''
Allows the /give command to accept amounts greater than the vanilla 100-stack limit.
When using /give with an amount that exceeds the item's stack limit times 100 (e.g., /give @s minecraft:dirt 100000), the mod cancels the vanilla limit check and distributes the items across as many stacks as needed, respecting the item's natural stack size.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
