org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.8.9
forge_version=11.15.1.2318
mappings=stable_22

## Mod Properties
mod_id=createtnt
mod_name=Create TNT
mod_license=All-Rights-Reserved
mod_version=1.0.0
mod_group_id=asd.itamio
mod_authors=Itamio, Asd1281yss
mod_description=A mod that makes tnt explode like create big cannon explosive shells, and adds realistic explosion physics and block gravity physics to the structure being exploded.
